name: Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@83375c56fcf7255e3977ea7aadce9b2bd9bfc208 # v2.4.1
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
